### model
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 64
lora_target: all

### dataset
dataset: UMIE_train
template: qwen3_vl
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: false
preprocessing_num_workers: 1
dataloader_num_workers: 16

### output
output_dir: LVLM_RUMIE/saves/Qwen3_VL_2B_UMIE
logging_steps: 10
save_steps: 38211
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 2.0e-5
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
report_to: tensorboard
dataset_dir: ./

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
